# Generated by Django 5.1.3 on 2024-12-02 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wine',
            name='year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='store.year'),
            preserve_default=False,
        ),
    ]
